### ISSUE TITLE
calculator-jquery example not working

### ISSUE THREAD

**Issue by MichaelGamel** [DanWahlin/TypeScriptDemos#1]
![screenshot_1](https://cloud.githubusercontent.com/assets/6534028/21879944/ad5ec0a0-d8a4-11e6-8071-adaaf0435cb1.png)

**Comment by DanWahlin** [comment]
Thanks - jquery.js simply wasn't checked it. Changed it to use a CDN path so if you grab the latest code base it should be working now.
